logo: /5. Attachment/LOGO.png
theme: jekyll-theme-minimal
title: Tremor Cancellor
description: This is the website for Team 4's final project in the 2024-1 Introduction to Design of Medical Robots and Devices(SNU). Team Member are Dahyun Nam, SengUk Mun, Mingshan He, and Juntae Han. 
show_downloads: true
google_analytics:

github:
  zip_url: http://example.com/download.zip
  another_url: another value